# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Engineering.ai.test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Engineering.ai.test
   pod 'AlamofireJsonToObjects'
   pod 'SVProgressHUD'
   pod 'UIScrollView-InfiniteScroll'

end
